### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by KatieMFritz** [comment]
Looking forward to reviewing this, but there's no hosted site yet! 😬 

I'm not seeing a `gh-pages` branch in your repository either. Did you type `git push origin master:gh-pages` in your terminal? Did you get any error messages?

Don't forget to check your links before you submit in the future! ✔️

**Comment by harr1193** [comment]
Fixed it, it is hosted to gh-pages now, https://harr1193.github.io/MI-449-SS17-741-html-atom-and-basic-elements-JmL5o8/

**Comment by KatieMFritz** [comment]
Great start, Kyle! 🌟 

### Use headings appropriately

> Each of the following elements is used appropriately, at least once: `h1`, `**h2**`, `p`, `img`, `li`, `a`

Headings are for giving structure to our webpages - kind of like creating an outline. They're most commonly used for titles of sections.

You used `h1` LIKE A BOSS.  It's used for the name of the page. Great job.

Two things to change:
1. In your resume, "Qualifications" (line 3) is the name of a section, so it should be `h2`. You'll be able to get rid of `strong`, because the browser will make it bold by default. 
2. This is a stylistic opinion, but I don't think the photo introduction counts as a section name. I would just use a regular `p` element to caption the photo. Feel free to argue with me, though!

### Make image clickable

> At least one external image is used and links to the page it came from

By this, we mean that *the image itself* should be the link to the page the image came from. Check out "Making images clickable" on [page 6 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-atom-and-basic-elements/6) if you're not quite sure what I mean. The image will be inside the `a` tags. 

Let me know when you've made changes, and I'll give it another look. 😄

**Comment by harr1193** [comment]
The changes have been made.

**Comment by KatieMFritz** [comment]
Very close! Push the changes to your `gh-pages` branch too.

**Comment by harr1193** [comment]
I keep forgetting to do that sorry, it is hosted now.

**Comment by KatieMFritz** [comment]
It's okay, I forget too. 😄 

IT'S DONE YOU DID IT!!!!! 🎉 

:shipit:

**Comment by KatieMFritz** [comment]
By the way - nice job with your commit messages for this project. There are a couple that are a bit vague, but each commit message is unique and most are very clear on what you changed. This habit will make your life much easier down the road! 😄
